widgets corresponding to francisco
Francisco-V98/buscampz_flutter pull request #12
Opened 2024-06-19 22:43 UTC by Francisco-V98

**list of created widgets:** 

-   **AppBar**
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/cec45cd1-1a8c-49a6-8684-84c18ee0f3e4)

- **Card incidence list**
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/10686fc7-2716-4fe5-baa2-4dfb341c0009)

- **Incidence Section** _( User Data and Detail incidence)_
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/6b1c49f1-7c6f-4b46-9d7e-b6f3129d6f2a)

- **BottomSheet Section** _(Button bs, group btn bs and bs buscampz)_
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/b172b50a-82ce-4652-9e4a-ce0539fc0f54)
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/dae907fc-74ce-4d5b-b9c8-e6c41088638a)

**extra tasks**
- add color palette
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/57891293-9760-4b93-b90c-72026a91dadd)

- add text styles
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/482943c6-ca1a-47c9-818f-e7f060d28bef)

- create the color system for dark and light mode
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/dfe96947-c532-4cc0-b23b-a7d3815f9b45)

2024-06-21 02:46 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +import 'package:flutter/material.dart';
Vamos de lo core a menos core, material va de primero

2024-06-21 02:46 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +  // final String image;
eliminar comentario

2024-06-21 02:48 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +  final bool withBackground;
esto lo entiendo mucho, si queremos algo dinámico el backenground deberíamos sestear una imagen o color, y en base a si lo agregar se muestra o no, igual comentario para el de abajo

2024-06-21 02:49 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +  final IconData iconRight;
aqui, por ejemplo, deja como opción iconRight, si no lo setean es opcionall

2024-06-21 02:49 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +    // required this.image,
eliminar comentario

2024-06-21 02:49 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +    this.iconRight = Icons.menu_rounded,
mantener el orden de las contantes y la inicialización, están diferentes

2024-06-21 02:50 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +      color: withBackground ? AppColors.bgTopLight : Colors.transparent,
aqui en este componente como sabes que es light o dark mode?

2024-06-21 02:51 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +                : const SizedBox(height: 48, width: 48),
esto es para que cuando no se setee se mantenga el tamaño para el title?

2024-06-21 02:51 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +              style: AppTextStyles.h4_20(AppColors.black)
este black cambia entre light y dark mode?

2024-06-21 02:53 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +  final String image;
por el titulo pense que se podia confirgurar el border, el nombre me parece que si describes un componente por sus caracterisca no escala, ya que podrías llegar a tener 20 características

2024-06-21 02:53 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart
> +import 'package:flutter/material.dart';
ordenar imports

2024-06-21 02:54 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart
> +  final String titleBs;
no se abrevia Bs, adicional si el componente se llama BottomSheet no hace falta que agregues Bs, y quita todo lo que sea With---- esto, por el comentario de arriba

2024-06-21 02:55 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart
> +    this.titleBs = 'Title Here',
en el mundo real, es mejor dejarlo en blanco o un titulo que tenga sentido, si esto lo ven en prod se ve raro.

2024-06-21 02:55 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart
> +              : const SizedBox.shrink(),
que hace esto?

2024-06-21 02:56 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/button_bottom_sheet.dart
> +import 'package:flutter/material.dart';
arregla todos los imports

2024-06-21 02:56 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/button_bottom_sheet.dart
> +class ButtonBottomSheet extends StatelessWidget {
Boton de Abajo, que quisiste decir con este componentes?

2024-06-21 02:57 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/button_bottom_sheet.dart
> +    return InkWell(
Porque InWell y no gesture detector?

2024-06-21 02:58 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/button_bottom_sheet.dart
> +      onTap: onTap,
se bloquea si se presiona muchas veces?

2024-06-21 02:58 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/group_buttons_bottom_sheet.dart
> +class GroupButton extends StatelessWidget {
si hablas de group, button debris ser prural

2024-06-21 02:59 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/group_buttons_bottom_sheet.dart
> +class GroupButton extends StatelessWidget {
este componente no recibe nada?

2024-06-21 03:00 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/group_buttons_bottom_sheet.dart
> +          onTap: () {},
deja un ejemplo del onte tap, cuando hagas una clase de ejemplo, colócale example, me confundi pensando que era la clase principal

2024-06-21 03:03 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/cards/card_incidence_list.dart
> +class CardIncidenceList extends ConsumerWidget {
Si este es el componente tienes que hacerlo sin riverpod, el gestor del estado no lo maneja el componente, sino la clase que lo implementa

2024-06-21 03:04 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/cards/card_incidence_list.dart
> +  final String image;
en otro lugar usaste ImageData, debes tener concordancia

2024-06-21 03:05 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/cards/card_incidence_list.dart
> +    final colorTheme = ref.watch(appColorThemeProvider);
ya vi para que lo usaste, esto no va aqui, se hace sin esto

2024-06-21 03:13 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/detail_incidence.dart
> +            //TODO need to add the btn of jesus
//TODO: para que se marque

2024-06-21 03:14 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/detail_incidence.dart
> +class _IconAndNumber extends StatelessWidget {
Estos nombre son raros, que hace esto?

2024-06-21 03:14 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/detail_incidence.dart
> +  final int number;
int es un numero, eso es claro, pero para que es ese numero

2024-06-21 03:18 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/user_data_incidence.dart
> +        boxShadow: [
Los componentes puedes dejar un comentario de detalle de lo mas resáltate, aqui no hay nada

2024-06-21 03:19 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/user_data_incidence.dart
> +                ),
evaluar separar los widgets

2024-06-21 03:20 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/widgets.dart
> +export 'package:buscampz_flutter/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart';
si es un export se llama export, no se lo colocaste, ahora, tampoco es tener todo, porque quieres esto todo aqui junto?

2024-06-21 03:20 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/widgets.dart
> +export 'package:buscampz_flutter/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart';
Busca como documentar con comentarios

2024-06-21 03:21 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/config/colors/app_colors_theme.dart
> +  AppColorTheme(this.isDarkMode);
no funciona asi, ve como esta en Busbanz

2024-06-21 03:21 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/config/router/routers.dart
> +          path: '/appbar',
crea un enum, para los path

2024-06-21 03:22 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/config/router/routers.dart
> +          path: '/appbar',
esto es el example?

2024-06-21 03:23 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/example/example_screens/screens.dart
> +export 'package:buscampz_flutter/buscampz_rayito_flutter_package/example/example_screens/bottom_sheet_screen.dart';
vuelvo, si es example, tiene que tener el nombre de example

2024-06-21 03:24 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/example/example_screens/list_components_screen.dart
> +        _CustomListTile(
usa el enum de location, y me parece que es para navegar. mejor para todos

2024-06-21 03:24 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/example/example_screens/app_bar_screen.dart
> +          AppBarBuscampz(title: 'Hola Mundo'),
hola mundo?

2024-06-21 03:25 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/example/example_screens/app_bar_screen.dart
> +          AppBarBuscampz(title: 'Hola Mundo'),
colócale una coma para que diente

2024-06-21 03:27 UTC, venganza147 requested changes
revisar

2024-06-21 12:12 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +      color: withBackground ? AppColors.bgTopLight : Colors.transparent,
Acá aún no se ha aplicado el tema de color, en dado caso solo dirá algo así… no tendrá sufijo light

`color: withBackground ? AppColors.bgTop : Colors.transparent,`

2024-06-21 12:14 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +                : const SizedBox(height: 48, width: 48),
Si exactamente si no está el icono, estará el espacio ocupado por un sizeBox

2024-06-21 12:16 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +              style: AppTextStyles.h4_20(AppColors.black)
Sí, se me había olvidado comentarte que los colores no están cambiados en todas las pantallas, solo en una sola, ahí en esos componentes toca actualizarles el color para que funcione tanto dark como light @venganza147

2024-06-21 12:40 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart
> +              : const SizedBox.shrink(),
te muestra un title o no

![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/af655733-3ea9-4ead-8b72-feeb481f8117)

![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/56c33fbd-c5c1-43fc-81a5-b3d9773a5a77)

2024-06-21 12:41 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/button_bottom_sheet.dart
> +class ButtonBottomSheet extends StatelessWidget {
el btn del bottomsheet

2024-06-21 12:44 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/button_bottom_sheet.dart
> +    return InkWell(
Quería que se viera con un efecto a la hora del tap pero no hizo nada

2024-06-21 12:45 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/button_bottom_sheet.dart
> +      onTap: onTap,
no se bloquea

2024-06-21 12:48 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/group_buttons_bottom_sheet.dart
> +class GroupButton extends StatelessWidget {
Ajuste el nombre a ButtonGroup… y no recibe nada hasta el momento

2024-06-21 12:52 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/cards/card_incidence_list.dart
> +class CardIncidenceList extends ConsumerWidget {
Acá es donde tengo el detalle del tema de color que tengo que corregir para evitar el riverpod

2024-06-21 12:54 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/cards/card_incidence_list.dart
> +  final String image;
Revise en todos lados, no vi lo de ImageData

2024-06-21 12:57 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/detail_incidence.dart
> +class _IconAndNumber extends StatelessWidget {
es ese peque;o componente que esta en rojo

![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/e10c0f8e-2ec3-4a19-8a3b-5e5b3017546c)

2024-06-21 12:58 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/detail_incidence.dart
> +  final int number;
![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/f7653f25-65dc-47e4-9caa-524cc10bbe44)

2024-06-21 13:02 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/widgets.dart
> +export 'package:buscampz_flutter/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart';
estoo no lo entendi

2024-06-21 13:03 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/config/router/routers.dart
> +          path: '/appbar',
Si es para example solamente

2024-07-05 12:33 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart
> +// class AppBarBuscampz extends StatelessWidget {
eliminar código comentado

2024-07-05 12:34 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/bottom_sheet_buscampz.dart
> +          if (title != null)
title.isNotEmpty

2024-07-05 12:35 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/button_bottom_sheet.dart
> +class BottomSheetButton extends StatelessWidget {
si es un componente colócale buscamos al final

2024-07-05 12:36 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/group_buttons_bottom_sheet.dart
> +class ButtonGroupBottomSheet extends StatelessWidget {
Deja claro cuales son las clases de ejemplo con un sufijo _example.

2024-07-05 12:36 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/buttom_sheet/group_buttons_bottom_sheet.dart
> +          onTap: () {},
no dejaste el ejemplo

2024-07-05 12:39 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/cards/card_incidence_list.dart
> +    final colorTheme = ref.watch(appColorThemeProvider);
no hiciste nada con esto, no va aqui

2024-07-05 12:40 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/cards/card_incidence_list.dart
> +    required this.title,
Para los componentes maneja todo opcional, y ve como se comporta el widget si no le envías los datos.

2024-07-05 12:42 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/user_data_incidence.dart
> +class UserDataIncidence extends StatelessWidget {
UserData? me causa ruido ese nombre. para que quieres este widget

2024-07-05 12:43 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/user_data_incidence.dart
> +                ),
lo evaluaste?

2024-07-05 12:43 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/components/widgets.dart
> +export 'package:buscampz_flutter/buscampz_rayito_flutter_package/components/appbar/app_bar_buscampz.dart';
Deja comentarios y clasificadlo en secciones

2024-07-05 12:44 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/config/router/routers.dart
>  import 'package:buscampz_flutter/buscampz_rayito_flutter_package/example/example_screens/example_screens.dart';
veo muchos imports, que pasa con los exports, están de adorno?

2024-07-05 12:45 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/example/example_screens/app_bar_screen.dart
> +class _Body extends StatelessWidget {
mejor ser mas explicito, BodyAppBarScreen,

2024-07-05 12:47 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/example/example_screens/incidence_section.dart
> +class IncidenceSectionScreen extends StatelessWidget {
Esto me parece muy global, si tienes 3 pantallas de incidents a que te refieres?

2024-07-05 12:47 UTC, venganza147 commented on lib/buscampz_rayito_flutter_package/example/example_screens/screens.dart
> +export 'package:buscampz_flutter/buscampz_rayito_flutter_package/example/example_screens/app_bar_screen.dart';
Clasificar y usar, veo muchos imports

2024-07-05 12:48 UTC, venganza147 reviewed
Revisar comentos

2024-07-05 12:53 UTC, merged

2024-07-05 16:39 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/cards/card_incidence_list.dart
> +    required this.title,
En este component no pueden ser opcionales todos, porque necesita esos datos para tener sentido, solo la foto puede ser opcional

2024-07-05 17:57 UTC, Francisco-V98 commented on lib/buscampz_rayito_flutter_package/components/incidence_section/user_data_incidence.dart
> +class UserDataIncidence extends StatelessWidget {
Es ese segmento que tiene la data del usuario en el view de la incidencia 

![image](https://github.com/Francisco-V98/buscampz_flutter/assets/156324130/a9fb9f86-54a4-468f-9900-08e660d775a4)